 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'timestamp' : Time,
  'authorPrincipal' : Principal,
  'postId' : bigint,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'isRead' : boolean,
  'imageUrl' : [] | [string],
  'senderPrincipal' : Principal,
  'timestamp' : Time,
  'recipientPrincipal' : Principal,
}
export interface Notification {
  'id' : bigint,
  '_type' : NotificationType,
  'isRead' : boolean,
  'fromPrincipal' : Principal,
  'message' : string,
  'timestamp' : Time,
  'postId' : [] | [bigint],
}
export type NotificationType = { 'dm' : null } |
  { 'like' : null } |
  { 'comment' : null } |
  { 'follow' : null };
export interface Post {
  'id' : bigint,
  'likeCount' : bigint,
  'timestamp' : Time,
  'caption' : string,
  'commentCount' : bigint,
  'imageBlobId' : string,
  'authorPrincipal' : Principal,
}
export interface Profile {
  'bio' : string,
  'displayName' : string,
  'avatarBlobId' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'avatarBlobId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
  'createPost' : ActorMethod<[string, string], bigint>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint, bigint, bigint], Array<Comment>>,
  'getExplorePosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFeedPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getLikeCount' : ActorMethod<[bigint], bigint>,
  'getLikedPosts' : ActorMethod<[], Array<bigint>>,
  'getMessages' : ActorMethod<[Principal, bigint, bigint], Array<Message>>,
  'getNotifications' : ActorMethod<[bigint, bigint], Array<Notification>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getProfiles' : ActorMethod<[Array<Principal>], Array<Profile>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserPosts' : ActorMethod<[Principal, bigint, bigint], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasLiked' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markConversationRead' : ActorMethod<[Principal], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProfiles' : ActorMethod<[string], Array<Profile>>,
  'sendMessage' : ActorMethod<[Principal, string, [] | [string]], bigint>,
  'toggleLike' : ActorMethod<[bigint], boolean>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];